-- TGuia Food - schema inicial Supabase
-- Banco principal: PostgreSQL / Supabase

create extension if not exists pgcrypto;

create type public.order_status as enum (
  'open',
  'closing',
  'closed',
  'cancelled'
);

create type public.order_type as enum (
  'table',
  'counter',
  'cashier',
  'delivery'
);

create type public.member_role as enum (
  'owner',
  'admin',
  'cashier',
  'waiter',
  'kitchen'
);

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  service_rate numeric(5,2) not null default 10.00 check (service_rate >= 0 and service_rate <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.member_role not null default 'waiter',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table public.restaurant_tables (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  number integer not null check (number > 0),
  name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, number)
);

create table public.product_categories (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  display_order integer not null default 0,
  color text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  category_id uuid references public.product_categories(id) on delete set null,
  code text,
  name text not null,
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0),
  active boolean not null default true,
  kitchen_print boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, code)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_number bigint generated by default as identity,
  custom_code bigint,
  order_type public.order_type not null default 'table',
  table_id uuid references public.restaurant_tables(id) on delete set null,
  status public.order_status not null default 'open',
  customer_name text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  opened_at timestamptz not null default now(),
  closing_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (order_type = 'table' and table_id is not null)
    or order_type <> 'table'
  )
);

create unique index orders_one_active_order_per_table
  on public.orders(table_id)
  where table_id is not null and status in ('open', 'closing');

create index orders_org_status_idx on public.orders(organization_id, status);
create index orders_table_idx on public.orders(table_id);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  notes text,
  kitchen_printed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index order_items_order_idx on public.order_items(order_id);

create table public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  method text not null,
  amount numeric(12,2) not null check (amount > 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index order_payments_order_idx on public.order_payments(order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger organizations_set_updated_at
before update on public.organizations
for each row execute function public.set_updated_at();

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger restaurant_tables_set_updated_at
before update on public.restaurant_tables
for each row execute function public.set_updated_at();

create trigger product_categories_set_updated_at
before update on public.product_categories
for each row execute function public.set_updated_at();

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create trigger order_items_set_updated_at
before update on public.order_items
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_org_member(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.organization_members m
    where m.organization_id = org_id
      and m.user_id = auth.uid()
      and m.active = true
  );
$$;

create or replace function public.can_manage_org(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.organization_members m
    where m.organization_id = org_id
      and m.user_id = auth.uid()
      and m.active = true
      and m.role in ('owner', 'admin')
  );
$$;

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_members enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_payments enable row level security;

create policy organizations_select_member
on public.organizations for select
to authenticated
using (public.is_org_member(id));

create policy organizations_update_admin
on public.organizations for update
to authenticated
using (public.can_manage_org(id))
with check (public.can_manage_org(id));

create policy profiles_select_self
on public.profiles for select
to authenticated
using (id = auth.uid());

create policy profiles_update_self
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy members_select_same_org
on public.organization_members for select
to authenticated
using (public.is_org_member(organization_id));

create policy members_manage_admin
on public.organization_members for all
to authenticated
using (public.can_manage_org(organization_id))
with check (public.can_manage_org(organization_id));

create policy tables_member_all
on public.restaurant_tables for all
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy categories_member_all
on public.product_categories for all
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy products_member_all
on public.products for all
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy orders_member_all
on public.orders for all
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy order_items_member_all
on public.order_items for all
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and public.is_org_member(o.organization_id)
  )
)
with check (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and public.is_org_member(o.organization_id)
  )
);

create policy order_payments_member_all
on public.order_payments for all
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_payments.order_id
      and public.is_org_member(o.organization_id)
  )
)
with check (
  exists (
    select 1 from public.orders o
    where o.id = order_payments.order_id
      and public.is_org_member(o.organization_id)
  )
);

-- Totais calculados no banco para evitar divergencia no frontend.
create or replace view public.order_totals
with (security_invoker = true)
as
select
  o.id as order_id,
  o.organization_id,
  coalesce(sum(oi.unit_price * oi.quantity), 0)::numeric(12,2) as subtotal,
  round(
    coalesce(sum(oi.unit_price * oi.quantity), 0)
    * coalesce(org.service_rate, 0) / 100,
    2
  )::numeric(12,2) as service_amount,
  round(
    coalesce(sum(oi.unit_price * oi.quantity), 0)
    * (1 + coalesce(org.service_rate, 0) / 100),
    2
  )::numeric(12,2) as total
from public.orders o
join public.organizations org on org.id = o.organization_id
left join public.order_items oi on oi.order_id = o.id
group by o.id, o.organization_id, org.service_rate;
